### ISSUE TITLE
VNode syntax error from UglifyJs

### ISSUE THREAD

**Issue by samuxyz** [developit/preact-compat#300] opened 2017-02-18 07:24 UTC
Hi!
I have been trying to replace React with Preact-Compat and in development mode it works smooth.
However when I uglify the bundle I receive the following error:

```
ERROR in bundle.js from UglifyJs
SyntaxError: Unexpected token: name (VNode) [bundle.js:182,4]
```

Line 182 is the following:

```
let VNode = __webpack_require__.i(__WEBPACK_IMPORTED_MODULE_1_preact__["h"])('a', null).constructor;
```

Btw, I installed preact and preact-compat and added the 2 aliases in my webpack config.

Any idea?

Thanks a lot!

**Comment by UnwrittenFun** [comment] 2017-02-18 09:18
I believe that uglify does not like es6, and therefore the `let`

It looks like webpack is including the code from the preact-compat `src` folder, rather than `dist`. On further investigation it seems like webpack 2 may now use the `jsnext:main` field in the package.json by default

You could change your aliases to point to the dist folder or use babel to transpile it yourself

Possibly related https://github.com/webpack/webpack/issues/4296

I think the documentation may need ammending, assuming this is the case.

**Comment by UnwrittenFun** [comment] 2017-02-18 11:56
Funnily enough, a few hours after commenting, I have just run into this exact problem myself.
This fixes it for me as expected.
```js
resolve {
  alias: {
    'react': 'preact-compat/dist/preact-compat.js',
    'react-dom': 'preact-compat/dist/preact-compat.js'
  }
}
```

**Comment by developit** [comment] 2017-02-18 17:22
Yup, this is because `webpack 2` uses `preact-compat`'s `src/` directory.  This issue is a duplicate of #155 - let's move discussion there :)

**Closed by developit** 2017-02-18 17:22 UTC

**Comment by samuxyz** [comment] 2017-02-19 05:17
Hey Guys,

Thank you both, I did fix it following the suggestions. You can close the issue as well.

**Comment by developit** [comment] 2017-02-19 20:27
@samuxyz For what it's worth, there should be a fix in for this now.

**Comment by bradennapier** [comment] 2017-02-22 01:29
Is it released?  I updated and still have this error.

**Comment by developit** [comment] 2017-02-22 01:35
Hmm - no, I'm not sure why I commented that (might have been thinking of a different issue).
