### ISSUE TITLE
createPortal replacing the destination node instead of apending

### ISSUE THREAD

**Issue by y-lohse** [developit/preact-compat#515] opened 2018-11-26 17:36 UTC
Hi, and thanks for working on `preact-compat`!

We just discovered that if the component passed to `createPortal` is empty or falsy, the destination DOM node is cleared. Here's a minimal reproduction : https://codesandbox.io/s/9qyr3klq7r
Replacing `<Void />` by `<NotVoid />` reverts to what we think is a normal behavior.

This doesn't see in line with how react behaves : https://codesandbox.io/s/new

Is this the expected behavior in `preact-compat` or is it a bug?

**Comment by developit** [comment] 2018-12-07 22:07
Hi Yannick!  It looks like a bug. Preact is having trouble rendering into the `body` in your example because there is already an application rendered there.

It looks like the issue is that preact-compat's `Portal` implementation uses the destructive version of `render()`, so it replaces the contents of `<body>` entirely rather than adding a new Element:
https://github.com/developit/preact-compat/blob/master/src/index.js#L143-L151

I think we can fix this by adding a Boolean `remove = false` flag that gets passed through `renderSubtreeIntoContainer()` and into `render()` to bypass the removal behavior.

**Comment by marvinhagemeister** [comment] 2019-11-01 11:39
This is fixed in Preact X. Make sure to alias `preact/compat` instead of `preact-compat`.

**Closed by marvinhagemeister** 2019-11-01 11:39 UTC
Labels: bug, help wanted
