### ISSUE TITLE
PropTypes validation doesn't take default props into consideration when rendered on server.

### ISSUE THREAD

**Issue by ctrlplusb** [developit/preact-compat#126] opened 2016-07-22 06:14 UTC
I'll try look at this one too.

**Comment by ctrlplusb** [comment] 2016-07-22 13:04
I'm thinking the issue here may actually lie in the `preact-render-to-string` module.  It's like the default props aren't being applied.  As stated, it's only in server rendering, client side all ok.

**Comment by developit** [comment] 2016-07-22 13:08
Confirmed, it's actually just not applying them. Good catch!

**Comment by developit** [comment] 2016-07-22 14:00
Closing this out since it's been moved to https://github.com/developit/preact-render-to-string/issues/5

**Closed by developit** 2016-07-22 14:00 UTC
