### ISSUE TITLE
Failed to execute 'insertBefore' on 'Node'

### ISSUE THREAD

**Issue by katopz** [developit/preact-compat#176] opened 2016-09-07 17:40 UTC
I'm at and trying `preact 6.0.2`, `preact-compat 3.0.1` with https://github.com/justinjung04/universal-boilerplate and found that when I click `Go to page` and click `Go to home` I will get an error

```
Uncaught (in promise) DOMException: Failed to execute 'insertBefore' on 'Node': The new child element contains the parent.
```

Maybe a bug?

**Comment by developit** [comment] 2016-09-07 20:09
Looks like it! I'll check into it.

**Comment by developit** [comment] 2016-09-10 23:00
@katopz - I think I have a fix for this locally! Will publish as soon as I have vetted it.

**Comment by developit** [comment] 2016-09-13 16:43
Fix is on its way. I'm going to close this one out since it's a duplicate of developit/preact#297 and the bugfix will be in that repo.

**Closed by developit** 2016-09-13 16:43 UTC
Labels: bug
