### ISSUE TITLE
Unique key of component causes extra elements to appear

### ISSUE THREAD

**Issue by andrewn** [developit/preact-compat#21] opened 2016-03-09 10:46 UTC
Hi,

I'm using `preact-compat` to implement a user survey. Each question has an associated "answer type" component that allows the user to enter an answer e.g. an input field, a range slider or some buttons.

If two questions follow each other that use the same answer component then the data from the last answer is not removed.

I've tried to use a unique key to force the replacement of the component but this causes two components to appear e.g. `<AnswerInput key={uniqueQuestionId} />`.

[Here's a test case on Codepen](http://codepen.io/andrewnicolaou/pen/KzzpeB?editors=0011). If you enter some text in the input and click increment, on every other click, I see 2 instances of the <Input /> component:

![](https://cloud.githubusercontent.com/assets/1762/13632771/af6b99f6-e5eb-11e5-8881-1b8e011dade0.png)

[The same example using React](http://codepen.io/andrewnicolaou/pen/dMMVJP?editors=0010) doesn't pass the `key` through as props but entering text and clicking "Increment" clears the text box.

Is there a better approach to this?

**Comment by developit** [comment] 2016-03-09 12:26
@andrewn this might be related to developit/preact#73 - currently my top priority. I appreciate the minimal example, I will use it as I test out a solution.

**Comment by developit** [comment] 2016-03-09 15:50
Confirmed, this is a duplicate of developit/preact#73. Will close this issue once the upstream is fixed and that version has been propagated to preact-compat.

**Comment by developit** [comment] 2016-03-09 16:55
@andrewn Just released [Preact 4.1.2](https://github.com/developit/preact/releases/tag/4.1.2) and preact-compat `1.6.1`, which I can confirm fixes this issue. Thanks!

Your pen running on preact-compat 1.6.1: http://codepen.io/developit/pen/EKKEvP
(Also just a tip: `wzrd.in/standalone/preact-compat` already bundles preact itself, so there's no need to re-include it)

**Closed by developit** 2016-03-09 16:55 UTC

**Comment by andrewn** [comment] 2016-03-10 08:57
Thanks!

**Comment by andrewn** [comment] 2016-03-10 10:39
@developit I think I've found another issue. Using the same example running [preact-compat 1.6.1](http://codepen.io/developit/pen/EKKEvP) do the following:

1. Enter some text into the input field
2. Click "Increment", the text disappears as expected
3. Click "Increment" again, the text is back
4. Repeat and the text is gone again.

Shall I raise this as another bug?

**Comment by developit** [comment] 2016-03-10 12:36
This happens because you are not setting a value for the input. Preact (currently) does not modify any attributes it has not been told about. 

So technically not a bug, but I think it's worth opening an issue on the Preact repo to start a discussion around whether the existing behavior is what we want. Certainly I can see a case for resetting input state at least.

**Comment by andrewn** [comment] 2016-03-10 13:23
The [same example using React](http://codepen.io/andrewnicolaou/pen/eZzNGK) does clear the input so I guess I expected preact-compat to do the same. 

I'll open an issue in preact as you suggest. :-)

Thanks for the quick reply!

**Comment by developit** [comment] 2016-03-10 13:27
Yup - React actually doesn't recycle DOM elements, so the second time the `<input>` is rendered (referenced) it's a fresh copy. Preact is a bit nuts about recycling (constant memory and all that).
