### ISSUE TITLE
react-google-recaptcha compatability

### ISSUE THREAD

**Issue by cameronbraid** [developit/preact-compat#225] opened 2016-10-13 05:06 UTC
The react-google-recaptcha module doesn't work with preact and preact-compat

I've added an example at https://github.com/cameronbraid/preact-compat-react-google-recaptcha with usage instructions.

Issues are as follows :

a) the async loading of the recaptcha script takes a long time - there is a cancelled attempt to download https://www.google.com/recaptcha/api2/anchor... then on the second attempt it succeeds and the recaptcha box is shown

b) once the captcha box is shown, any calls to setState causes the recaptcha box to dissapear - try entering something into the textbox, or complete the captcha

I couldn't get this to work in webpackbin/codepen etc... none of them allow the webpack resolve.alias for react and react-dom to preact-compat

Cheers

Cameron

**Comment by developit** [comment] 2016-10-13 13:03
Hmm - so the issue is actually that [react-google-recaptcha](https://github.com/dozoisch/react-google-recaptcha) is not preventing re-renders, which means Preact's diff recycles all the elements created by the recaptcha library within the created wrapper div.  I'll submit a PR to them.

**Comment by developit** [comment] 2016-11-07 03:03
@cameronbraid This will be fixed in the next release of Preact :)

**Comment by jgillich** [comment] 2016-12-04 22:40
A bit OT, but I just moved to preact and wrote [my own Recaptcha component](https://github.com/termbox/termbox/blob/c31ece0fd2dbd4aee5ee4284f563863e57536a97/app/components/Recaptcha.js). Much less code as well, not sure what react-async-script is even doing..

**Comment by developit** [comment] 2016-12-05 02:42
Should be fixed now anyway, 7.0 stopped removed foreign nodes. Closing but feel free to reopen if its still an issue.

**Closed by developit** 2016-12-05 02:42 UTC
Labels: has fix, preact core
